################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_can.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cec.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_comp.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2s.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_irda.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_iwdg.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_msp_template.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smbus.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tsc.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_usart.c \
D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_wwdg.c 

OBJS += \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_can.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cec.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_comp.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2s.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_irda.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_iwdg.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_msp_template.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smbus.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tsc.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_usart.o \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_wwdg.o 

C_DEPS += \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_can.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cec.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_comp.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2s.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_irda.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_iwdg.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_msp_template.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smbus.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tsc.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_usart.d \
./STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_wwdg.d 


# Each subdirectory must supply rules for building sources it contributes
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_adc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_can.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_can.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_can.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cec.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cec.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cec.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_comp.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_comp.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_comp.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_crc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dac_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2c_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2s.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2s.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_i2s.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_irda.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_irda.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_irda.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_iwdg.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_iwdg.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_iwdg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_msp_template.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_msp_template.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_msp_template.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pcd_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_rtc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smartcard_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smbus.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smbus.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_smbus.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_spi_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tsc.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tsc.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_tsc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_uart_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_usart.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_usart.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_usart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_wwdg.o: D:/Hexabitz\ Modules\ for\ testing\ 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_wwdg.c
	arm-none-eabi-gcc "$<" -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F091xC -DH01R0 '-D_module=1' -DSTM32F091RCx -DSTM32 -DSTM32F0xx -c -I"D:/Hexabitz Modules for testing 2/H01R0x/BOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/CMSIS_RTOS" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/Middleware/FreeRTOS/Source/portable/RVDS/ARM_CM0" -I"D:/Hexabitz Modules for testing 2/H01R0x/H01R0" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc/Legacy" -I"D:/Hexabitz Modules for testing 2/H01R0x/User" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/STM32F0xx_HAL_Driver/Inc" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Include" -I"D:/Hexabitz Modules for testing 2/H01R0x/Thirdparty/CMSIS/Device/ST/STM32F0xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"STM32F0xx_HAL_Driver/Src/stm32f0xx_hal_wwdg.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

